[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'

[[plugins]]
repo = 'jiangmiao/auto-pairs'

[[plugins]]
repo  = 'cespare/vim-toml'

[[plugins]]
repo = "peitalin/vim-jsx-typescript"
